#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: postgres
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#
app:
  database:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver: org.postgresql.Driver
  token:
    secret: secret
    expiration: 360000